-- Enable UUID extension
create extension if not exists "uuid-ossp";

-- 1. User Settings (Plan & Limits)
create table user_settings (
  user_id text primary key,
  openai_key text,
  plan text default 'SOLO',
  cards_used int default 0,
  card_limit int default 5,
  razorpay_customer_id text,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- 2. Integrations
create table user_integrations (
  id bigint generated by default as identity primary key,
  user_id text not null,
  provider text not null,
  access_token text not null,
  refresh_token text,
  metadata jsonb,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(user_id, provider)
);

-- 3. Task Cards
create table task_cards (
  id uuid default gen_random_uuid() primary key,
  user_id text not null,
  source_id text not null,
  category text,
  type text,
  title text,
  subtitle text,
  content text,
  tags text[],
  color_class text,
  status text default 'PENDING',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(user_id, source_id)
);

-- 4. RLS Policies
alter table user_settings enable row level security;
alter table user_integrations enable row level security;
alter table task_cards enable row level security;
create policy "Public Access" on user_settings for all using (true);
create policy "Public Access" on user_integrations for all using (true);
create policy "Public Access" on task_cards for all using (true);

-- 5. SEED DATA (Dummy Accounts)
-- Run this to pre-populate your DB with loginable users
insert into user_settings (user_id, plan, cards_used, card_limit) values 
('demo_user_free', 'SOLO', 3, 5),
('demo_user_pro', 'PRO', 42, 9999),
('demo_user_new', 'SOLO', 0, 5)
on conflict (user_id) do nothing;

insert into user_integrations (user_id, provider, access_token) values
('demo_user_pro', 'github', 'ghp_demo_token_pro'),
('demo_user_free', 'github', 'ghp_demo_token_free')
on conflict (user_id, provider) do nothing;